### PR TITLE
Implement local chess engine tuning script

### PR DESCRIPTION
**Pull request by kiudee**
The demand for an easy to use tuning interface to [bayes-skopt](https://bayes-skopt.readthedocs.io/en/latest/readme.html) has been/is high. As a first step towards that goal, this pull request aims to implement all the plumbing required. In addition, the end result will be a first usable tuning script using a command line interface.

Todo
-----

- [x] Implement a cutechess-cli result parser
- [x] Implement a configurable experiment runner supporting
  - Time control matches (increment/no-increment, mixed time control)
  - Fixed nodes
- [x] A configurable command line interface supporting
  - [x] Passing of tunable parameters
  - [x] Passing of fixed parameters
  - [x] Save/Resume functionality (including changed ranges)
- [ ] ~~Support for multiple time controls (using interleaving)~~ (postponed)
- [x] Correctly return all debug output by cutechess-cli
- [x] Atomic safe and backups for chain file
- [x] Example tuning configurations to get people started
- [x] Output current tuning result every nth iteration
- [x] Support plotting of the optimization landscape every nth iteration

### CODE REVIEW

**Comment by Claes1981** [comment]
Hi,
Testing this branch through:
`pip install --editable "git+https://github.com/kiudee/chess-tuning-tools.git@local_tuner#egg=chess-tuning-tools"` 

It would be nice with an example of the required "tuning-config" json file. 
Maybe there are some hints in test_io.py? But is also the time control supposed to be specified in the tuning-config file?

**Comment by kiudee** [comment]
Thank you for testing the branch. I have uploaded my current testing configuration file here:
https://gist.github.com/kiudee/08d9f4d5604e8223e950a05a8ed686ce

So to run a test tune you need:
```
.
├── network_weights.gz
├── conf.json
├── lc0.exe
├── openings-dd-8ply-2000.pgn
└── sf.exe
```

Part of this branch will also be a variety of tuning configurations (one minimal, one with all possible options) and documentation of the options.

**Comment by Claes1981** [comment]
Thanks,

I get an error:
`Error parsing UCI tuples:`
`setoption name Move Overhead value 300`

Maybe because of the space in the "Move Overhead" option?

command:
`tune local --tuning-config Test2_config.json --data-path Test2.npz --logfile Test2.log --resume --verbose`

Test2_config.json:

```
{
	"engines": [
		{
			"command": "/partitions/Sandisk/xfs/media/data/chess/engines/Stockfish_development_versions/stockfish_19071415_bmi2_pgo",
			"fixed_parameters": {
				"SyzygyPath": "/partitions/nvme/xfs/chess/Syzygy",
				"Contempt": 11,
				"Move Overhead": 300
			}
		},
		{
			"command": "/partitions/Sandisk/xfs/media/data/chess/engines/Leelafish/Leelafish-0.8/leelafish-08-cuda10289-cudnn765",
			"fixed_parameters": {
				"Backend": "cudnn-fp16",
				"WeightsFile": "/partitions/Sandisk/xfs/media/data/chess/engines/Lc0/weights/Sergio-V/256x20-t40-1541.pb.gz",
				"NNCacheSize": 800000,
				"MoveOverheadMs": 2000,
				"AuxEngineFile": "/partitions/Sandisk/xfs/media/data/chess/engines/Stockfish_development_versions/stockfish_19071415_bmi2_pgo",
				"AuxEngineOptions": "Hash=1024;Threads=6;Contempt=11;SyzygyPath=/partitions/nvme/xfs/chess/Syzygy;SyzygyProbeDepth=4;Move Overhead=300;Ponder=false"
			}
		}
	],
	"parameter_ranges": {
		"Threads": "Integer(1, 6)",
		"SyzygyProbeDepth": "Integer(1, 100)",
		"SyzygyProbeLimit": "Integer(0, 7)",
		"Hash": "Integer(1, 8192)"
	},
    "engine1_tc": "15+15",
    "engine2_tc": "15+15",
    "opening_file": "empty.pgn",
    "adjudicate_draws": false,
    "adjudicate_resign": false
} 
```

(My ultimate goal is to find good parameters of https://github.com/killerducky/lc0/wiki/LeelaFish on my own computers (and given time control), and first step is to find good parameters for the auxiliary engine Stockfish. In my own local testing I get better results for LeelaFish with default values than for Lc0 so far.)

**Comment by kiudee** [comment]
Good catch, I made the RegEx more robust there.

**Comment by Claes1981** [comment]
The tune process is stuck at max CPU for 6 hours at updating model:
```
2020-07-14 23:57:37,949 INFO     Got score: 0.2857142857142857 +- 0.10480484252255876
2020-07-14 23:57:37,949 INFO     Updating model
/partitions/Sandisk/xfs/media/data/downloads/chess/chess-tuning-tools-local_tuner-pip_git/env/lib64/python3.8/site-packages/sklearn/gaussian_process/kernels.py:275: RuntimeWarning: overflow encountered in exp
  params[hyperparameter.name] = np.exp(
2020-07-14 23:58:25,045 INFO     GP sampling finished (47.095579s)
2020-07-14 23:58:25,045 DEBUG    GP kernel: 0.0865**2 * Matern(length_scale=[0.259, inf, inf, inf], nu=2.5) + WhiteKernel(noise_level=0)
2020-07-14 23:58:25,047 INFO     Starting iteration 39
2020-07-14 23:58:25,047 INFO     Testing {'Threads': 6, 'SyzygyProbeDepth': 57, 'SyzygyProbeLimit': 3, 'Hash': 3051}
2020-07-14 23:58:25,048 DEBUG    engines.json is prepared:
[{'command': '/partitions/Sandisk/xfs/media/data/chess/engines/Stockfish_development_versions/stockfish_19071415_bmi2_pgo', 'name': 'engine1', 'initStrings': ['setoption name SyzygyPath value /partitions/nvme/xfs/chess/Syzygy', 'setoption name Contempt value 11', 'setoption name Move Overhead value 300'], 'protocol': 'uci'}, {'command': '/partitions/Sandisk/xfs/media/data/chess/engines/Leelafish/Leelafish-0.8/leelafish-08-cuda10289-cudnn765', 'name': 'engine2', 'initStrings': ['setoption name Backend value cudnn-fp16', 'setoption name WeightsFile value /partitions/Sandisk/xfs/media/data/chess/engines/Lc0/weights/Sergio-V/256x20-t40-1541.pb.gz', 'setoption name NNCacheSize value 800000', 'setoption name MoveOverheadMs value 2000', 'setoption name AuxEngineFile value /partitions/Sandisk/xfs/media/data/chess/engines/Stockfish_development_versions/stockfish_19071415_bmi2_pgo', 'setoption name AuxEngineOptions value Hash=1024;Threads=6;Contempt=11;SyzygyPath=/partitions/nvme/xfs/chess/Syzygy;SyzygyProbeDepth=4;Move Overhead=300;Ponder=false'], 'protocol': 'uci'}]
2020-07-14 23:58:25,048 INFO     Start experiment
2020-07-15 00:01:24,244 INFO     Experiment finished (179.195777s elapsed)
2020-07-15 00:01:24,244 DEBUG    Raw result:
Indexing opening suite...
Started game 1 of 2 (engine1 vs engine2)
Finished game 1 (engine1 vs engine2): 1/2-1/2 {Draw by 3-fold repetition}
Score of engine1 vs engine2: 0 - 0 - 1  [0.500] 1
Started game 2 of 2 (engine2 vs engine1)
Finished game 2 (engine2 vs engine1): 1/2-1/2 {Draw by 3-fold repetition}
Score of engine1 vs engine2: 0 - 0 - 2  [0.500] 2
Elo difference: 0.0 +/- 0.0, LOS: nan %, DrawRatio: 100.0 %
Finished match


2020-07-15 00:01:24,533 INFO     Got score: -1.3877787807814457e-17 +- 0.059517123621030385
2020-07-15 00:01:24,533 INFO     Updating model
/partitions/Sandisk/xfs/media/data/downloads/chess/chess-tuning-tools-local_tuner-pip_git/env/lib64/python3.8/site-packages/sklearn/gaussian_process/kernels.py:275: RuntimeWarning: overflow encountered in exp
  params[hyperparameter.name] = np.exp(
2020-07-15 00:02:12,987 INFO     GP sampling finished (48.453403s)
2020-07-15 00:02:12,987 DEBUG    GP kernel: 0.0887**2 * Matern(length_scale=[0.253, inf, inf, inf], nu=2.5) + WhiteKernel(noise_level=0)
2020-07-15 00:02:12,990 INFO     Starting iteration 40
2020-07-15 00:02:12,990 INFO     Testing {'Threads': 1, 'SyzygyProbeDepth': 66, 'SyzygyProbeLimit': 5, 'Hash': 312}
2020-07-15 00:02:12,990 DEBUG    engines.json is prepared:
[{'command': '/partitions/Sandisk/xfs/media/data/chess/engines/Stockfish_development_versions/stockfish_19071415_bmi2_pgo', 'name': 'engine1', 'initStrings': ['setoption name SyzygyPath value /partitions/nvme/xfs/chess/Syzygy', 'setoption name Contempt value 11', 'setoption name Move Overhead value 300'], 'protocol': 'uci'}, {'command': '/partitions/Sandisk/xfs/media/data/chess/engines/Leelafish/Leelafish-0.8/leelafish-08-cuda10289-cudnn765', 'name': 'engine2', 'initStrings': ['setoption name Backend value cudnn-fp16', 'setoption name WeightsFile value /partitions/Sandisk/xfs/media/data/chess/engines/Lc0/weights/Sergio-V/256x20-t40-1541.pb.gz', 'setoption name NNCacheSize value 800000', 'setoption name MoveOverheadMs value 2000', 'setoption name AuxEngineFile value /partitions/Sandisk/xfs/media/data/chess/engines/Stockfish_development_versions/stockfish_19071415_bmi2_pgo', 'setoption name AuxEngineOptions value Hash=1024;Threads=6;Contempt=11;SyzygyPath=/partitions/nvme/xfs/chess/Syzygy;SyzygyProbeDepth=4;Move Overhead=300;Ponder=false'], 'protocol': 'uci'}]
2020-07-15 00:02:12,991 INFO     Start experiment
2020-07-15 00:08:49,011 INFO     Experiment finished (396.019692s elapsed)
2020-07-15 00:08:49,012 DEBUG    Raw result:
Indexing opening suite...
Started game 1 of 2 (engine1 vs engine2)
Finished game 1 (engine1 vs engine2): 1/2-1/2 {Draw by fifty moves rule}
Score of engine1 vs engine2: 0 - 0 - 1  [0.500] 1
Started game 2 of 2 (engine2 vs engine1)
Finished game 2 (engine2 vs engine1): 1-0 {White mates}
Score of engine1 vs engine2: 0 - 1 - 1  [0.250] 2
Elo difference: -190.8 +/- nan, LOS: 15.9 %, DrawRatio: 50.0 %
Finished match


2020-07-15 00:08:49,299 INFO     Got score: 0.14285714285714285 +- 0.07097855559025883
2020-07-15 00:08:49,299 INFO     Updating model
```
There is also warnings about overflow at the iterations before that.

Do I need to adjust some of the options (shown by "tune local --help) from the defaults for my specific parameter_ranges?
Also some general guidelines for the options would be nice to have in the documentation.

command:
`tune local --tuning-config Test3_config.json --data-path Test3.npz --logfile Test3.log --resume --verbose`

Test3_config.json:
```
{
	"engines": [
		{
			"command": "/partitions/Sandisk/xfs/media/data/chess/engines/Stockfish_development_versions/stockfish_19071415_bmi2_pgo",
			"fixed_parameters": {
				"SyzygyPath": "/partitions/nvme/xfs/chess/Syzygy",
				"Contempt": 11,
				"Move Overhead": 300
			}
		},
		{
			"command": "/partitions/Sandisk/xfs/media/data/chess/engines/Leelafish/Leelafish-0.8/leelafish-08-cuda10289-cudnn765",
			"fixed_parameters": {
				"Backend": "cudnn-fp16",
				"WeightsFile": "/partitions/Sandisk/xfs/media/data/chess/engines/Lc0/weights/Sergio-V/256x20-t40-1541.pb.gz",
				"NNCacheSize": 800000,
				"MoveOverheadMs": 2000,
				"AuxEngineFile": "/partitions/Sandisk/xfs/media/data/chess/engines/Stockfish_development_versions/stockfish_19071415_bmi2_pgo",
				"AuxEngineOptions": "Hash=1024;Threads=6;Contempt=11;SyzygyPath=/partitions/nvme/xfs/chess/Syzygy;SyzygyProbeDepth=4;Move Overhead=300;Ponder=false"
			}
		}
	],
	"parameter_ranges": {
		"Threads": "Integer(1, 6)",
		"SyzygyProbeDepth": "Integer(1, 100)",
		"SyzygyProbeLimit": "Integer(0, 7)",
		"Hash": "Integer(1, 8192)"
	},
    "engine1_tc": "10+1",
    "engine2_tc": "10+1",
    "opening_file": "empty.pgn",
    "adjudicate_draws": false,
    "adjudicate_resign": false
} 
```

Thanks for your work on a very interesting tool!

**Comment by kiudee** [comment]
Looking at the kernel, it is clear that the parameters diverged:
```python
Matern(length_scale=[0.253, inf, inf, inf], nu=2.5
```
I will take a look at all the default parameters, if there is a problem.

**Comment by kiudee** [comment]
@Claes1981 found the problem in bayes-skopt. Will upload a patch there soon.

**Comment by kiudee** [comment]
Upgrading [bask](https://pypi.org/project/bask/) to 0.7.0 should fix that problem.

**Comment by Claes1981** [comment]
Thanks,

Now all the length_scale parameters remain on about the same low size. 
However, the tune process still get stuck after updating the model a couple of iterations. When working, the tune process uses 100% cpu (all available threads) while updating the model, but when stuck it seems to only use 1 thread at max. The WhiteKernel noise_level goes to zero before the tune get stuck. Is it supposed to do that?

After aborting the tune (Ctrl-C), and then resuming it, it continue to work more iterations (still going... current iteration 51..) and the noise_level seems more or less stable around 10⁻8 to 10⁻10

**Comment by kiudee** [comment]
The parameters of the kernel look good now. The noise level is sensible, since it only captures the residual noise. 
```
Got score: -1.3877787807814457e-17 +- 0.059604927352530125
```
Here you can see the standard error it estimates for the score estimate.

At which iteration did it stall? The way it is programmed right now, the tuner starts with `n_initial_points=30` quasi-random iterations. Then it performs a detailed fit of the model with `gp_initial_burnin=100` many samples, which can take slightly longer than the subsequent iterations. Or does it stall completely?

**Comment by Claes1981** [comment]
Okay, this time it stalled on or after iteration 37. I only waited maybe 1 to 3 minutes before pressing Ctrl-C this time, but before todays patch I waited about 6 hours before pressing Ctrl-C 11 days ago.

**Comment by kiudee** [comment]
@Claes1981 I added the output for the current optimum to the tuner. By default it will do so every 5th iteration, but it can be changed using the parameter `--result-every`.

**Comment by Claes1981** [comment]
After last commit (use atomic write) it crashes with this output:
```
2020-07-26 17:50:51,569 INFO     GP sampling finished (0.000151s)
2020-07-26 17:50:51,569 DEBUG    GP kernel: None
Traceback (most recent call last):
  File "/partitions/Sandisk/xfs/media/data/downloads/chess/chess-tuning-tools-local_tuner-pip_git/env/bin/tune", line 33, in <module>
    sys.exit(load_entry_point('chess-tuning-tools', 'console_scripts', 'tune')())
  File "/partitions/Sandisk/xfs/media/data/downloads/chess/chess-tuning-tools-local_tuner-pip_git/env/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/partitions/Sandisk/xfs/media/data/downloads/chess/chess-tuning-tools-local_tuner-pip_git/env/lib64/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/partitions/Sandisk/xfs/media/data/downloads/chess/chess-tuning-tools-local_tuner-pip_git/env/lib64/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/partitions/Sandisk/xfs/media/data/downloads/chess/chess-tuning-tools-local_tuner-pip_git/env/lib64/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/partitions/Sandisk/xfs/media/data/downloads/chess/chess-tuning-tools-local_tuner-pip_git/env/lib64/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/partitions/Sandisk/xfs/media/data/downloads/chess/chess-tuning-tools-local_tuner-pip_git/env/src/chess-tuning-tools/tune/cli.py", line 353, in local
    np.savez_compressed(f, np.array(X), np.array(y), np.array(noise))
  File "<__array_function__ internals>", line 5, in savez_compressed
  File "/partitions/Sandisk/xfs/media/data/downloads/chess/chess-tuning-tools-local_tuner-pip_git/env/lib64/python3.8/site-packages/numpy/lib/npyio.py", line 686, in savez_compressed
    _savez(file, args, kwds, True)
  File "/partitions/Sandisk/xfs/media/data/downloads/chess/chess-tuning-tools-local_tuner-pip_git/env/lib64/python3.8/site-packages/numpy/lib/npyio.py", line 720, in _savez
    with zipf.open(fname, 'w', force_zip64=True) as fid:
  File "/usr/lib64/python3.8/zipfile.py", line 1516, in open
    return self._open_to_write(zinfo, force_zip64=force_zip64)
  File "/usr/lib64/python3.8/zipfile.py", line 1613, in _open_to_write
    self.fp.write(zinfo.FileHeader(zip64))
TypeError: write() argument must be str, not bytes
Exception ignored in: <function ZipFile.__del__ at 0x7f4db829f9d0>
Traceback (most recent call last):
  File "/usr/lib64/python3.8/zipfile.py", line 1820, in __del__
    self.close()
  File "/usr/lib64/python3.8/zipfile.py", line 1837, in close
    self.fp.seek(self.start_dir)
ValueError: I/O operation on closed file.
```

**Comment by Claes1981** [comment]
After commit "Fix atomic write using mode "wb" the crash output is different:
```
2020-07-26 18:15:37,136 INFO     Updating model
2020-07-26 18:15:37,136 INFO     GP sampling finished (0.000152s)
2020-07-26 18:15:37,137 DEBUG    GP kernel: None
Traceback (most recent call last):
  File "/partitions/Sandisk/xfs/media/data/downloads/chess/chess-tuning-tools-local_tuner-pip_git/env/bin/tune", line 33, in <module>
    sys.exit(load_entry_point('chess-tuning-tools', 'console_scripts', 'tune')())
  File "/partitions/Sandisk/xfs/media/data/downloads/chess/chess-tuning-tools-local_tuner-pip_git/env/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/partitions/Sandisk/xfs/media/data/downloads/chess/chess-tuning-tools-local_tuner-pip_git/env/lib64/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/partitions/Sandisk/xfs/media/data/downloads/chess/chess-tuning-tools-local_tuner-pip_git/env/lib64/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/partitions/Sandisk/xfs/media/data/downloads/chess/chess-tuning-tools-local_tuner-pip_git/env/lib64/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/partitions/Sandisk/xfs/media/data/downloads/chess/chess-tuning-tools-local_tuner-pip_git/env/lib64/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/partitions/Sandisk/xfs/media/data/downloads/chess/chess-tuning-tools-local_tuner-pip_git/env/src/chess-tuning-tools/tune/cli.py", line 352, in local
    with AtomicWriter(data_path, mode="wb", overwrite=True) as f:
AttributeError: __enter__
```

**Comment by kiudee** [comment]
I should be more careful with copy/pasting.

**Comment by Claes1981** [comment]
Thanks, it works now, no crash :)

**Comment by kiudee** [comment]
Good to hear - working on the example configurations and documentation in the meantime.

**Comment by Claes1981** [comment]
Any way to plot the data from chess-tuning-tools with Scikit-optimize's plot_objective function? 
242 iterations/484 games completed so far...

**Comment by kiudee** [comment]
That’s definitely on the agenda and easy to implement.

**Comment by kiudee** [comment]
@Claes1981 Added support for plotting to the tuner. Let me know if it works on your end. You need to set `--plot-every` to something like 1 or 5.

I also fixed an initialization problem for bayes-skopt, which I suspect caused your freezing problem. Try upgrading bask to 0.7.1.

**Comment by Claes1981** [comment]
Thanks, just tried the plots, they look very interesting!

In my current testing run (I plan to experiment with real tuning of Stockfish NNUE and longer time control on my computers later), the current optimum and the graphs swing wildly still after 370 iterations:

```
2020-07-26 22:05:02,744 INFO     Starting iteration 360
2020-07-26 22:05:05,972 INFO     Current optimum:
{'Threads': 5, 'SyzygyProbeDepth': 70, 'SyzygyProbeLimit': 4, 'Hash': 3508}
```

```
2020-07-28 06:53:08,270 INFO     Starting iteration 365
2020-07-28 06:53:12,481 INFO     Current optimum:
{'Threads': 6, 'SyzygyProbeDepth': 62, 'SyzygyProbeLimit': 2, 'Hash': 7185}
```

```
2020-07-28 07:00:03,660 INFO     Starting iteration 370
2020-07-28 07:00:07,788 INFO     Current optimum:
{'Threads': 5, 'SyzygyProbeDepth': 100, 'SyzygyProbeLimit': 7, 'Hash': 3026}
```

Too little effect on Elo by the parameters, too few samples, or do I need to adjust some of the tune command options from default?




Complete log:
[Test13c.log](https://github.com/kiudee/chess-tuning-tools/files/4986152/Test13c.log)

(upgraded Bask and Chess-tuning-tools after iteration 365)

**Comment by kiudee** [comment]
Indeed, the model at iteration 365 looks a bit more sensible whereas the one from 370 seems to be on the slight overfit side.

This is also apparent when looking at the log:
```
Before Iteration 365:
GP kernel: 0.00891**2 * Matern(length_scale=[0.333, 0.283, 0.364, 0.309], nu=2.5) + WhiteKernel(noise_level=0.00114)
Before Iteration 370:
GP kernel: 0.0577**2 * Matern(length_scale=[0.343, 0.335, 0.297, 0.178], nu=2.5) + WhiteKernel(noise_level=1.49e-07)
```
You can see the noise level dropped significantly while the 4th lengthscale (for the Hash parameter) also dropped.
More iterations will likely fix that.

**Comment by kiudee** [comment]
If you temporarily increase `--gp-burnin` to a higher values (10, 30, 50 or even 100), it will be able to recover more quickly with new observations (but the running time of each iteration slows down).

**Comment by Claes1981** [comment]
Thanks for the advice, I will test when I come home tonight :)

**Comment by kiudee** [comment]
@Claes1981 I was stress-testing the script with different tunes and I am able to replicate the stalling now. I think the main culprit seems to be an underestimated noise with a subsequent divergence.

**Comment by Claes1981** [comment]
Okay, it stalled for about 20 minutes on one thread at updating model after iteration 377 yesterday evening. And then I experienced for the first time it suddenly continue by itself with iteration 378 only to stall again for at least 20 minutes after iteration 379. Then I pressed Ctrl-C since I needed to go to bed and wanted to run a cutechess-cli gauntlet over night.

I don't think it is a big problem if you can watch the computer since you can just press Ctrl-C and then resume, but maybe  more problematic if you want to leave the computer for a day or more...

**Comment by Claes1981** [comment]
Are there an easy way to see how sure the tuner is on the current optimum values? For example 95% confidence bounds?
It would be interesting to be able to specify and check the confidence bounds yourself, personally I think the 50% confidence bound is interesting to see. 
I guess the kernel length_scale is correlated to the confidence bounds, but can you compute the percentage bounds from it?

**Comment by kiudee** [comment]
There is `Optimizer.expected_optimality_gap()` which estimates how close the optimum is to the best possible value.

Something like a confidence region is possible, but is a costly operation. We basically have to repeatedly sample functions consistent with the data from our model, determine the optimum in that sample and do that often enough to have a representative distribution.

**Comment by Claes1981** [comment]
Okay, would it be possible to (perhaps optionally) compute it only when stopping or pausing (for example by Ctrl-C) the tuner? Or would it take hours to compute?

**Comment by kiudee** [comment]
That’s certainly possible. An additional problem is how to represent the confidence region, since it can be non-convex and skewed. We could output a [contour plot](https://matplotlib.org/3.1.3/gallery/images_contours_and_fields/contour_demo.html#sphx-glr-gallery-images-contours-and-fields-contour-demo-py), but that might be difficult to interpret in more than 2 dimensions.

Another option could be to simply treat each dimension independently and just calculate a 95% confidence interval for it - ignoring the higher dimensional structure. As an indicator for uncertainty that could be enough.

**Comment by Claes1981** [comment]
Spontaneously I think the last option sounds good as well (if it can tell something about the confidence). I feel I would need to study statistics a lot more to feel sure how relevant or irrelevant the last option would be compared to the first option. :)

**Comment by Claes1981** [comment]
I have noticed that you have increased the default number of rounds per iteration to 5 (=10 games). That seems to resolve the stalling issue, I have not experience the stalling with 5 rounds per iteration so far. And 5 rounds are no problem for short time controls.
However, I assume that if you interrupt a running match (by Ctrl-C), for example after 4 completed rounds of 5, those 4 rounds need to be replayed from the beginning if you want to resume the tune later? That, I think, is problematic if you tune with longer time controls. (I have for example previously completed 1 650 games in a CLOP run where the median game length took about 50 minutes.) You might want to pause the tuning if you need to do other stuff on the computer, preferably without loosing many hours run of tuning doing so.

I therefore made some further tests with _"rounds": 1_ in the config file, but the stalling comes back. 
(I also tested to add "--gp-burnin 100", but that did not help. I guess that was just to prevent the optimum to swing to much.)

I guess to implement saving of the partial result of a multi-round match would need a lot of coding. Any other more simple solution to avoid the stalling, while keeping the rounds to 1 per iteration?

**Comment by kiudee** [comment]
I just uploaded a new patch to the bayes-skopt repository which should fix the stalling issue (bask=0.7.2). Can you try that one?

**Comment by Claes1981** [comment]
Sure, testing now (resuming the last test)!

**Comment by kiudee** [comment]
With that patch I think that the tuner works quite well and should be ready for a first release.

There are a few improvements I am thinking about, such as:

- Output the confidence intervals for the parameters
- Support for reducing the tuning ranges (increasing already works)
- Support passing in prior parameters (only for experts, but useful nonetheless)
- Support plotting for 1 dimension.
- More information output from a finished model
- Allow the user to query the model (e.g. "What is the optimal configuration if ParamX = 0.5?")
- and more

**Comment by Claes1981** [comment]
Yes, seems very promising 20 iterations without that I have experienced any stalling so far :)
I also notice that the WhiteKernel noise_level does not go to zero any more.

**Pull request merged**
